# Site settings
timezone: Europe/Berlin

baseurl: '/fontface-generator' # the subpath of your site, e.g. /blog/
url: 'http://cginternals.github.io' # the base hostname & protocol for your site

title: 'OpenLL - Font Face Generator'

languages: [ 'en' ]

# Handling Reading
safe: true
encoding: utf-8

# Build settings
markdown: kramdown

# Outputting
exclude: [
  'backup',
  'vendor',
  'LICENSE',
  'README.md']

# CSS Minification
sass:
  style: compressed
